---
- name: Install Metricbeat
  hosts: webservers
  become: true
  tasks:

  - name: Download Metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Install Metricbeat
    command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

  - name: Edit Metricbeat Config file
    copy:
      src: /etc/ansible/install-metricbeat/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: Enable and configure docker module
    command: sudo metricbeat modules enable docker

  - name: Setup Metricbeat
    command: sudo metricbeat setup

  - name: Start Metricbeat
    command: sudo service metricbeat start

  - name: Enable service metricbeat on boot
    systemd:
      name: metricbeat
      enabled: yes